# Source: cert-manager/templates/psp-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata: # kpt-merge: /cert-manager-psp
  name: cert-manager-psp
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "controller"
    app.kubernetes.io/version: "v1.8.2"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v1.8.2
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - cert-manager
