# Source: cert-manager/templates/cainjector-psp-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: /cert-manager-cainjector-psp
  name: cert-manager-cainjector-psp
  labels:
    app: cainjector
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "cainjector"
    app.kubernetes.io/version: "v1.8.2"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v1.8.2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-cainjector-psp
subjects:
  - kind: ServiceAccount
    name: cert-manager-cainjector
    namespace: cert-manager
